nci-hcmi-catalog/portal

- ui/package.json
- ui/src/components/Search.js
- ui/yarn.lock
Closes #20 
requires https://github.com/overture-stack/arranger/pull/336
> export tsv: date in filename

- ui/src/components/TableEntity.js
- ui/src/providers/SavedSets.js
> remove check for no set if no sqon

- ui/src/theme/index.js
- Color pallete on chart is missing lightest color.  Adjusting
> adjusting lightest palette color

- ui/package-lock.json
- ui/package.json
- ui/src/components/Quicksearch.js
- ui/src/components/Search.js
- ui/src/components/charts/PrimarySiteChart.js
- ui/src/components/charts/TopVariantsChart.js
- ui/src/theme/index.js
- ui/yarn.lock
still need to make the x-axis labels align better
> variant chart

- ui/src/components/VariantTables.js
Variant Table not updating on next/prev model change #101
> Added modelName as update param for variant table re-render

- ui/src/components/Model.js
- ui/src/utils/apiDataProcessor.js
- ui/src/utils/modelImageProcessor.js
Display -- in entity page if field has no value #96 
If you can think of a better way of doing this I'm open. I'd want to process the entire state tree in one go but because some the fields are processed as dates or yes/no it doesn't seem possible to simplify that much and so I went with the "more control" option.
> apiDataProcessor util func to process empty data to '--'

- data_model/model/properties.mapping.js
> 57 fix quicksearch

- api/package.json
- api/yarn.lock
- ui/package.json
- ui/src/components/Quicksearch.js
- ui/yarn.lock
This along with https://github.com/overture-stack/arranger/pull/421 fixes quicksearch
> Fix quicksearch

- ui/src/components/VariantTables.js
> :sparkles: VariantTables: add gene column

- ui/src/components/VariantTables.js
> order variant tables by frequency

- cms/package.json
- cms/src/data/import/SheetsToMongo.js
- cms/src/index.js
- npm script for getToken
- accept mutliple sheets: take sheet id and tab name in url
- add new models that are not found
Closes #120
> :sparkles: cms - only update modified data

- package-lock.json
- ui/package.json
- ui/src/components/Search.js
- ui/src/components/charts/GrowthChart.js
- ui/src/components/charts/PrimarySiteChart.js
- ui/src/components/charts/TopVariantsChart.js
- ui/yarn.lock
- Better chart responsiveness
- Click on bar/slice never removes SQON
Closes #115
> Chart updates

- ui/src/components/modals/ModelListModal.js
- ui/src/theme/modelListModalStyles.js
> 150 model list font bug

- cms/src/validation/model.js
- ui/src/components/admin/Model/AdminModelNav.js
- ui/src/components/admin/Model/ModelSingle.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/ModelSingleHeader.js
- ui/src/components/admin/config.js
- ui/src/components/admin/index.js
- ui/src/theme/adminControlsStyles.js
- ui/src/theme/adminModelStyles.js
- ui/src/theme/adminStyles.js
> Feat/149 edit-pre populate model form

- ui/src/components/admin/AdminTable/AdminTableController.js
- ui/src/components/admin/AdminTable/AdminTableToolbar.js
- ui/src/components/admin/AdminTable/EnhancedReactTable.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/VariantsManager/VariantColumns.js
- ui/src/components/admin/VariantsManager/VariantManagerTable.js
- ui/src/components/admin/VariantsManager/VariantsManager.js
- ui/src/components/admin/VariantsManager/index.js
* Refactors Admin Table
* Scaffolding for Variants
> :sparkles: Adds Variants table and controls

- ui/src/components/Model.js
add "customUnits" array for displaying units not in arranger
closes #199
> 199 add "days to split" as unit for "growth rate"

- ui/src/components/admin/Model/ModelImages.js
- ui/src/components/admin/Model/ModelSingleController.js
it's not beautiful but it's done
closes #167
> :sparkles: edit image meta

- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/ModelsManager/ModelManagerTable.js
- ui/src/components/admin/ModelsManager/ModelsManager.js
- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/helpers/index.js
- ui/src/components/admin/helpers/modelForm.js
- ui/src/components/admin/helpers/modelManagerAsyncs.js
- ui/src/components/admin/helpers/modelSingleAsyncs.js
- ui/src/components/admin/helpers/notifications.js
Bulk Model Uploaded results in notifications toaster #255
> Bulk uploader for models now operating as variants uploader

- ui/public/index.html
- ui/src/components/admin/AdminTable/DataTable.js
- ui/src/components/admin/Model/AdminModelNav.js
- ui/src/components/admin/Model/ModelForm.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/ModelsManager/ModelColumns.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/ModelsManager/ModelManagerTable.js
- ui/src/components/admin/UsersManager/UserManagerTable.js
- ui/src/components/admin/UsersManager/UserTableColumns.js
- ui/src/components/admin/UsersManager/UsersManager.js
- ui/src/components/admin/helpers/fetchTableData.js
- ui/src/components/admin/helpers/queryFilters.js
- ui/src/components/admin/helpers/tableActions.js
- ui/src/components/admin/schema/model.js
- ui/src/components/admin/schema/user.js
- ui/src/components/admin/services/GoogleLink.js
- ui/src/index.css
* Fixes table pagination
* Fixes tables filtering: filtering is now server side
> Table pagination and filter fixes

- cms/src/schemas/constants.js
update esophogeal --> esophogus
> update esophogeal --> esophogus

- ui/src/components/Model.js
Problems where the values had been localeString formatted. Now handled!
> 🐛 Fix math for days to split

- cms/src/helpers/matchedModels.js
- cms/src/helpers/modelStatus.js
- cms/src/hooks.js
- cms/src/routes/action.js
- cms/src/routes/bulk.js
- cms/src/schemas/descriptions/model.js
- cms/src/schemas/model.js
- cms/src/services/elastic-search/publish.js
- cms/src/services/elastic-search/update.js
- cms/src/validation/matchedModels.js
- cms/src/validation/model.js
- ui/src/components/Model.js
- ui/src/components/ModelBar.js
- ui/src/components/Search.js
- ui/src/components/TableExpandedCell.js
- ui/src/components/TableMatchedModelsCell.js
- ui/src/components/admin/Model/ModelForm.js
- ui/src/components/charts/MultipleModelsChart.js
- ui/src/components/queries/AggregationQuery.js
- ui/src/components/queries/ModelListModalQuery.js
- ui/src/components/queries/ModelQuery.js
- ui/src/theme/index.js
In progress but working, more styling fixes needed in Model page and Search Table
Publishing API works but there may be a bug in the publishing of models in the new matched set.
CMS can manage expanded. The element for matched models is added but it isn't connected yet.
> Matched Model/Expanded publishing and UI (WIP)

- cms/src/schemas/model.js
- cms/src/validation/model.js
- package.json
- scripts/arranger_metadata/aggs-state.json
- scripts/arranger_metadata/columns-state.json
- scripts/arranger_metadata/extended.json
- scripts/searchIndex.json
- ui/src/components/FormComponents.js
- ui/src/components/TableMatchedModelsCell.js
- ui/src/components/admin/Model/MatchedModelsFormComponent.js
- ui/src/components/admin/Model/ModelForm.js
- ui/src/components/admin/Model/ModelSingle.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/actions/ActionsMenu.js
- ui/src/components/admin/Model/actions/PublishModel.js
- ui/src/components/admin/ModelsManager/ModelColumns.js
- ui/src/components/admin/PublishLinkedModelsModal/PublishLinkedModelsModal.js
- ui/src/components/admin/helpers/modelSingleAsyncs.js
- ui/src/icons/ClearXIcon.js
- ui/src/theme/formComponentsStyles.js
Clear button in autocomplete form field
Popup confirmation when publishing a model that has matched models that will also be published
Error message when providing a name that is already registered
> Missing features for matched models

- ui/src/components/admin/DataDictionary/DependentFieldValuesGroup.js
- ui/src/components/admin/DataDictionary/DictionaryController.js
- ui/src/components/admin/DataDictionary/DictionaryDependentFieldValues.js
- ui/src/components/admin/DataDictionary/DictionaryFieldValues.js
- ui/src/components/admin/DataDictionary/EditableFieldValue.js
- ui/src/theme/adminDictionaryStyles.js
Handle errors related to editing fields:
- editing to blank
- editing to the same as an existing value
Also fixed a UI bug found in #609 
- set max-length on dependent value heading
> :bug: Handle Editable Field Errors & Edge Cases

- cms/src/helpers/uploadTemplate.js
- cms/src/routes/templates.js
- ui/src/components/admin/BulkUpload/BulkUploadInput.js
- ui/src/components/admin/helpers/googleSheets.js
- ui/src/components/admin/services/GoogleLink.js
- ui/src/theme/adminBulkUploadStyles.js
- ui/src/theme/adminNavStyles.js
This allows the creation of google sheet bulk upload template that has validation rules added based on current dictionary.
> Generate Bulk Upload Templates on Google Sheets

- cms/src/helpers/uploadTemplate.js
- cms/src/routes/templates.js
- ui/src/components/admin/BulkUpload/BulkUploadInput.js
- ui/src/components/admin/helpers/googleSheets.js
Bulk Variant Upload modal has link to generate a tempalte for variant uploads, CMS is able to generate this in google sheets.
> ✨ Variant Bulk Upload Template generation

- cms/src/helpers/uploadTemplate.js
- cms/src/routes/templates.js
- ui/src/components/admin/BulkUpload/BulkUploadInput.js
- ui/src/components/admin/helpers/googleSheets.js
* ✨ Variant Bulk Upload Template generation
* 👌 Error log message fix
> ✨ Variant Bulk Upload Template generation (#630)

- ui/src/components/charts/GrowthChart.js
- ui/src/components/charts/MultipleModelsChart.js
- ui/src/components/charts/PrimarySiteChart.js
> 🐛 Change cursor when hovering segments of the pie graphs (#492)

- cms/src/helpers/uploadTemplate.js
Typos in header fix upload issue.
> 🐛 Fix variant template header spelling

- scripts/esUtils.js
ES Connection details is also read from pm2
> 🔧 Fix es connection config in scripts

- api/package.json
- api/src/dataExport.js
- ui/package.json
- yarn.lock
Log errors
Upgrade arranger to fix bug.
> Fix Table Export

- ui/src/components/Model.js
- ui/src/components/Search.js
- ui/src/components/VariantTables.js
- ui/src/providers/Variants.js
- ui/src/theme/carouselStyles.js
- ui/src/theme/modelStyles.js
- ui/src/theme/searchStyles.js
* 💄 Change size of empty model details card (#664)
* 💄 Fix width of model details page table headers
* 💄 Resize 'x' icons in Available Molecular Characterizations table
* 💄 Re-order Available Molecular Characterizations table headers (#664)
* 💄 Prevent "jumping" when applying filters on model search page (#664)
* 🐛 Force re-render of model image carousel to make sure slider buttons show up when needed (#664)
* 🐛 Fix bug preventing full data list from showing in Variants Table (#664)
- ♻️ Refactor VariantTable component to use hooks instead of react-component-component
- 🐛 Fix bug where filtering then un-filtering the list of variants resulted in not all the data being rendered
* ✨ Add clear button to Variants Table search input (#664)
* ✨ Set active variant tab to "Histopathological" if …
> 🎨 Address Model Details Page Feedback (#664)

- scripts/arranger_metadata/columns-state.json
- ui/src/components/ModelBar.js
Removing from UI until all parts of feature are prepared.
> Disable Expanded in UI

- cms/src/routes/images.js
- cms/src/services/s3/s3.js
- scripts/migrateImages.js
- ui/src/components/admin/Model/ModelImages.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/modals/ModelListModal.js
- ui/src/components/queries/ModelListModalQuery.js
* 🐛 Fix Model List images
* 🐛 Dismiss upload banner and display error message when image uploads fail
> 🐛 Fix Model List Images & Handle Failed Image Uploads (#723)

- ui/src/components/charts/GrowthChart.js
- ui/src/components/charts/MultipleModelsChart.js
- ui/src/components/charts/PrimarySiteChart.js
- ui/src/components/charts/TopVariantsChart.js
- ui/src/components/charts/index.js
- ui/src/components/search/Search.js
Now based off of `feat/gvi` ✨ Still need to pull the correct data, though...
* Update styling of TopVariantsChart
* Enable TopVariantsChart on Search page
* 📝 Explain what new maxY function does for TopVariantsChart
> ✨ Front-end work for 'Most Frequently Mutated Genes' Chart (#670)

- docs/BulkUploadData.md
Fix regression bug which cause blank rows in tsv extracts of search table.
> Release 1.5.2

- ui/src/components/admin/Model/ModelVariants.js
- ui/src/theme/horizontalTabStyles.js
* Also fix border style for horizontal tabs
> 💄 Update Research Variants label to Research Somatic Variants (#660)

- ui/src/components/admin/BulkUpload/BulkUploadInput.js
- ui/src/components/admin/BulkUpload/BulkUploadModal.js
- ui/src/components/admin/BulkUpload/BulkUploadResult.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/ModelVariants.js
Update the Bulk Upload Modal from `Variants` ➡️  `Clinical Variants`
> 💄 Update Bulk Upload Modal to reference Clinical Variants (#733)

- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/actions/ImportGenomicVariants.js
* Update model status after fetching latest genomic variant data
* Change 'clear' request to be a POST instead of a GET
> 🐛 Update model status on genomic variant import

- cms/src/helpers/genomicVariants.js
- cms/src/schemas/model.js
- cms/src/services/gdc-importer/VariantImporter.js
- elasticsearch/arranger_metadata/extended.json
- elasticsearch/modelsIndex.json
Also fixes the mapping type for counts in search table, fixing the search to numeric instead of alpha
> Add filename and import date to gene_metadata

- ui/src/components/admin/AdminTable/Toolbar.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/theme/adminTableStyles.js
- ui/src/theme/horizontalTabStyles.js
- Update styling for genomic variant table header, move "Clear List" button
- Add genomic variant import metadata (import filename and timestamp) to genomic variant table header
> 💄 Styling updates for Variants tables in CMS (#660) (#662)

- ui/src/components/VariantTables.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/modals/ConfirmationModal.js
* Add custom `sortMethod` for 'Gene' column of genomic variant table on Model Details page
> 🐛 Sort 'Gene' column of genomic variant table by gene name (#756)

- ui/src/components/VariantTables.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/charts/TopVariantsChart.js
- ui/src/providers/Variants.js
- ui/src/theme/adminTableStyles.js
- ✨ Add empty state for Research Somatic Variants table in CMS (#764)
- 🔇 Remove unnecessary logging in TopVariantsChart
- 🐛 Fix bug in ModelVariants preventing gene metadata from displaying correctly
- ✨ Add empty state for Research Somatic Variants table in Model Details page (#764)
> Handle "No Variants Found in MAF" Cases on Front-End (#764)

- api/package.json
- ui/package.json
- ui/src/components/TextInput.js
- ui/src/components/admin/AdminTable/DataTable.js
- yarn.lock
Pending Arranger PR: https://github.com/overture-stack/arranger/pull/616
* ♿️ No longer auto-focus on aggs input fields
* ♿️ Add labels to table checkboxes
> ♿️ a11y updates from Arranger fixes

- ui/src/components/charts/GrowthChart.js
- ui/src/theme/index.js
* Add new colour for 'Other' in growthChartPalette
* Display non-2D and non-3D growth on the growth chart as 'Other'
* Minor typo fix in libreFranklin font-face declaration
> ✨ Add 'Other' Growth to 2D vs 3D Growth Chart

- ui/package.json
- ui/src/components/search/Search.js
- ui/src/theme/searchStyles.js
- yarn.lock
* Bump @arranger/components to v 2.10.0
* Enable new multi select dropdown with Select All/Reset to Defaults
> ⬆️ Upgrade Arranger UI, enable new dropdown menu (#826)

- ui/package.json
- ui/public/index.html
Adding the Adobe DTM tags to start of the `<head>` and end of the `<body>`, as per: https://github.com/nci-hcmi-catalog/portal/issues/832
> 📈 Add Adobe DTM Tags (#832)

- ui/src/components/search/Search.js
Disabling the Expanded/Unexpanded Toggle from the Search page until the feature is ready. Will re-enable once given approval.
> 🚩 Temporarily disable Expanded/Unexpanded Toggle (#831)

- ui/package.json
- ui/src/components/VariantTables.js
- ui/src/components/admin/AdminTable/DataTable.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/ModelsManager/ModelManagerTable.js
- ui/src/components/admin/UsersManager/UserManagerTable.js
- ui/src/components/search/Search.js
CMS Tables store PageSize
Variant Tables on model pages store page Size
Also brings in Arranger Components update to do row selection storage.
> Session Storage in non-arranger tables

- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js
- ui/src/components/modals/ConfirmMafFileModal.js
* Update handling of duplicate individual import notifications
* Trigger import status fetch after resolving conflicts for an import with multiple MAFs
> 🐛 Fix bug preventing import errors from being resolved on individual imports (#893)

- ui/src/components/InfoTooltip.js
- ui/src/components/Model.js
- ui/src/components/VariantTables.js
- ui/src/components/search/Search.js
- ui/src/components/tooltips/InfoTooltip.js
- ui/src/components/tooltips/index.js
- ui/src/theme/modelStyles.js
- ui/src/theme/searchStyles.js
* Adds Hover Bubbles to Model Details page
* Adds descriptions of each variant type above variant tables
* Adds Hover Bubbles to Search Table column headers
> ✨ Add informational tooltips (aka "Hover Bubbles") to Model Details page and Search table (#891 #906)

- ui/src/theme/modelStyles.js
Quick styling fix for links inside of hover bubbles.
> 🐛 Fix link styling inside hover bubbles (#907)

- ui/package.json
- yarn.lock
* Resolves issue where columns with custom headers would appear as blank rows in the column selection dropdown
> ⬆️  Upgrade to Arranger v2.12.16

- ui/package.json
- ui/src/components/search/Search.js
- ui/src/components/tooltips/index.js
- yarn.lock
**🐛 Facet header tooltip bugfixes**
* Fix bug causing facet header tooltips to extend beyond the window when scrollbars are present
* Fix z-index conflict causing facet header tooltip icons to appear above search facet results
**⬆️ Upgrade Arranger to v2.13.1**
* Fixes a bug with all boolean aggregation facets
> 🐛 Facet header tooltip bugfixes

- ui/src/components/VariantTables.js
- ui/src/components/tooltips/index.js
- ui/src/theme/modelStyles.js
Updates variant tooltips to specify the type (clinical, histopathological, research somatic)
> 💬 Update variant-related tooltip text (#928)

- api/package.json
- ui/package.json
- ui/src/components/VariantTables.js
- ui/src/components/search/Search.js
- ui/src/components/tooltips/index.js
- ui/src/theme/modelStyles.js
- yarn.lock
- Arranger update to fix missing header text in TSV export
- Formatting and text changes in tooltips
> Release 1.11.1

- ui/src/utils/cartDownload.js
- Cart Download uses arranger displayValue configurations
> Final updates for 1.11.1

- ui/src/components/VariantTables.js
- ui/src/utils/cartDownload.js
- ui/src/utils/tsvDownloader.js
* Allow specification of column order in exported clinical variants TSVs
> ✨ Add Column Ordering to Clinical Variants TSV Download (#930)

- ui/src/components/search/GeneSearch.js
- ui/src/components/search/Search.js
- ui/src/components/tooltips/index.js
- ui/src/theme/searchStyles.js
* Rename search facet "Genes" to "Altered Gene(s)"
* Rename search facet "Type" to "Model Type"
* Add a tooltip to the newly renamed "Search by Altered Gene(s)" facet
> 💄 UI Updates to Support Mutated Gene Count Change (#957)

- cms/src/helpers/authorizeUserAccess.js
- cms/src/index.js
- yarn.lock
🐛 Fix False Positives in Auth Check
* Use `async/await` to ensure User lookup promise evaluates, prevent auth check from returning false positives
* Add additional logging around unauthorized requests
In order to deploy these changes, the following steps need to be run:
1. Restart the `cms` service
>  🔖 Release 1.14.1

- README.md
Updating README to reflect new version requirements for NodeJS, Elasticsearch, and MongoDB.
> 📝 Update Version Numbers in Documentation

- ui/src/components/input/Toggle/Toggle.js
- ui/src/components/search/Search.js
Activates the Expanded/Unexpanded Toggle component on the Search page table.
No additional deploy steps required.
> Activate Expanded/Unexpanded Models Toggle (#1024)

- cms/package.json
- cms/src/routes/sync-data.js
- cms/src/services/import/SheetsToMongo.js
- cms/src/validation/model.js
- package.json
- yarn.lock
* Upgrades `yup` validation package to v1.0.0
* Updates Save and Publish validation to allow all optional fields to be set to `null`
1. Clear the existing node_modules: `rm -rf node_modules cms/node_modules ui/node_modules`
2. Deploy the new tag through Jenkins
3. Restart the cms service
> 🦺 Make Non-Required Fields Nullable (#623)

- elasticsearch/arranger_metadata/aggs-state.json
* Enables the Search Facet for "Tissue Status"
In order to deploy these changes, the following steps need to be run:
1. Run the `updateEs` script
```
ENV={env} npm run updateEs
```
> 🔧 Enable "Tissue Status" as a Search Facet (#1059)

- api/package.json
- ui/package.json
- ui/src/theme/searchStyles.js
- yarn.lock
* Upgrades Arranger to latest 2.x v2.19.4
* Updates Arranger style overrides to hide facet "Search" icon when the facet is collapsed
> 💄 Hide Search Icon When Facets Are Closed (#632)

- cms/src/helpers/genomicVariants.js
Point to GDC v1 in Sequence URL for models populated by GDC importer.
> 🐛 Update Automatic Sequence URL Builder to Point to GDC v1

- cms/src/helpers/genomicVariants.js
- cms/variant-migrations/migrations/20240226184341-update-models-gdc-v1-sequence-urls.js
* [🐛 Update Automatic Sequence URL Builder to Point to GDC v1](https://github.com/nci-hcmi-catalog/portal/pull/1068) 
No additional steps required for this deploy.
> 🔖 Release 1.22.3
