nci-hcmi-catalog/portal

- ui/src/components/Header.js
revert small header, because nci branding guidelines require padding around logo @rosibaj
> revert small header

- CONTRIBUTING.md
This contributing guide is the one we've settled with overtime, with more specific info on the whole rebasing master weirdness.
@cy you would know for sure if I missed something / made a mistake
@lepsalex the flow is slightly unusual, but the main idea is to never miss a hotfix.
It's the "no next / develop" version of our already modified version, so tags are king for releases, and master is "next". 
Also we like to keep the commit history clean if possible, so always rebasing your pull request against master is preferred, or simply using the `squash and merge` or `rebase and merge` button in github's pull request is ideal.
Thanks!
[markdown view](https://github.com/nci-hcmi-catalog/portal/blob/contributing/CONTRIBUTING.md)
> 📗 modified GDC contributing guide

- ui/src/components/Model.js
- ui/src/utils/apiDataProcessor.js
It occurred to me how to do apiDataProcessing step in a nicer way while looking through the arranger code. Arranger has an 'extended mapping' feature which allows non-dev users to specify display type, display name and units for the data table on the search page. There's no reason why the entity pages can't use the same settings! Switches models entity page to use extended mapping, and only calls `apiDataProcessing() ` once :tada:
only update to arranger needed is that 'days' needs to be added to units, only 'week, month, year' currently
> :recycle: refactor apiDataProcessor to use extended mapping

- ui/src/components/queries/ModelListModalQuery.js
- ui/src/utils/apiDataProcessor.js
fields with number type were showing up as '--', i guess at one point they were being passed as strings from arranger so it worked; now they are passed as numbers so the data.length fails. Looks like dates are still passed as strings.
> :bug: apiDataProcessor: properly handle number types

- cms/src/routes/sync-data.js
Forgot that Francois asked for this during the demo meeting. 
errors now look like 
```
"errors": {
"gender": "gender must be one of the following values: female, male, unspecified, unknown",
"race": "race must be one of the following values: american indian or alaskan native, asian, black or african american, native hawaiian or other pacific islander, white, not reported, unknown"
},
```
instead of 
```
"errors": [
"gender must be one of the following values: female, male, unspecified, unknown",
"race must be one of the following values: american indian or alaskan native, asian, black or african american, native hawaiian or other pacific islander, white, not reported, unknown"
],
```
> :sparkles: validation errors: key by path

- cms/src/index.js
- cms/src/routes/sync-data.js
OK. Ended up on not using onError hook of express-restify-mongoose because I have all sorts of problems when using it, like an undefined key error on https://github.com/florianholzapfel/express-restify-mongoose/blob/master/src/errorHandler.js#L8 on `req.params.id` on POSTs, and the handler returning an HTML error page instead of JSON even though I did 
```
onError: (err, req, res, next) => {
const statusCode = req.erm.statusCode // 400 or 404
res.status(statusCode).json({
message: err.message
})
}
``` 
just like the documentation says. But setting res.status(400).json inside the preCreate and preUpdate hooks behave much better. So,
```
POST http://localhost:8001/api/v1/Model
Content-Type: application/json
Body
{
"model_name": "HCM-BROD-9989.C08",
"model_type":"3-D: Other (neurosphere)", …
```
> :sparkles: preCreate, preUpdate validate

- cms/package.json
- cms/src/index.js
- cms/src/routes/images.js
- yarn.lock
This adds /images endpoint to upload, read and delete images. Uses mongo GridFSbuckets which creates 2 collections,`images.chuncks` and `images.files` which stores metadata. Filename and image file is sent in one request using `Content-Type: multipart/form-data`
Upload:
```
curl -X POST \
http://localhost:8001/images \
-H 'cache-control: no-cache' \
-H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
-H 'postman-token: fcb8f299-b435-4f21-29f2-2ceb63f7c9d1' \
-F filename=worried_cat \
-F image=@fw9y2gaxmhc11.jpg
```
response:
```
{
"id": "5b5b7a34832031494ee8bace",
"filename": "worried_cat"
}
```
Read
`GET http://localhost:8001/images/5b5b7a34832031494ee8bace `
Delete
`DELETE http://localhost:8001/images/5b5b7a34832031494ee8bace`
> :sparkles: 145 CR_D api for images

- cms/package.json
- cms/src/routes/images.js
- yarn.lock
Uses https://github.com/lovell/sharp to resize, does not require any runtimes eg. imagemagick to be installed :tada: 
ex:
`http://localhost:8001/api/v1/images/5b7db1725ef8372d17895bbb?w=100&h=100`
not including either w or h autosizes.
Closes #145
> :sparkles: resize images on the fly

- cms/src/schemas/model.js
- ui/src/components/Model.js
- ui/src/components/admin/Model/ModelImages.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/queries/ModelQuery.js
i admit the err of my ways and renamed file.file_name and file.file_type so we don't have to update the mappings, except add an "id" field to files. Still haven't seen the images in there yet because my arranger decided to break again...but it should work (maybe).
> rename back file_name and file_type

- cms/package.json
- yarn.lock
After adding migrate-mongo to project, we can use it directly in portal-ci
#245
> Add migrate-mongo binary

- cms/src/validation/model.js
Only mandatory due to form validation, no model schema enforcement.
> CMS no longer requires age at diagnosis

- cms/src/schemas/constants.js
- cms/src/schemas/descriptions/model.js
- ui/src/components/Model.js
- ui/src/components/admin/Model/ModelForm.js
- `Link to Distributor` instead of Distributor Part Number
- Update CMS description for Distributor ID
- typo in Tissue type value `Pre-malignant`
> 🐛 Update spelling and word choice for new fields

- ui/src/components/admin/DataDictionary/DependentFieldValuesGroup.js
- ui/src/components/admin/DataDictionary/DictionaryDependentFieldValues.js
- ui/src/components/admin/DataDictionary/DictionarySidebar.js
- ui/src/components/admin/helpers/dictionary.js
- 🐛 Fix the "Expand All" button, make it toggle to a "Collapse All" button as well
- 🐛 Filter the "Editable Fields" list against a list of fields that are actually editable
> 🐛 Fix "Expand All" button & filter Editable Fields list (#591)

- cms/src/schemas/descriptions/model.js
- ui/src/components/admin/DataDictionary/DependentFieldValuesGroup.js
- ui/src/components/admin/DataDictionary/DictionaryController.js
- ui/src/components/admin/DataDictionary/DictionaryFieldValues.js
- ui/src/components/admin/DataDictionary/DictionaryHeader.js
- ui/src/components/admin/DataDictionary/DictionarySidebar.js
- ui/src/components/admin/DataDictionary/EditableFieldValue.js
- ui/src/components/admin/helpers/dictionary.js
- ui/src/theme/adminDictionaryStyles.js
- ui/src/theme/adminModalStyles.js
Fixed bugs for #551 #555 and #556 :
- Set `cursor: pointer` on modal close icon
- Re-add the "Split Ratio" field
- Add error handling to Editable Dictionary and show success notification/toast on publish
- Fix bug where Editable Fields weren't updating state/value after Draft Publish/Reset
- Fix bug preventing multiple edits of the same Editable Field per draft
- Fix bug preventing multiple edits of the same dependent field in one draft
Also made some front-end changes based on feedback:
- Change grammar on "edited" text in sidebar to match the header
- Change Model Details "Type" label to "Model Type" for consistency
- Move "Last updated" timestamp below "Last published" timestamp in header
Also refactored the "add", "edit", and "remove" functionality to use the same function for both …
> 🐛 Bug Fixes for #551 #555 and #556

- ui/src/components/FormComponents.js
- ui/src/components/admin/DataDictionary/DataDictionary.js
- ui/src/components/admin/DataDictionary/DictionaryController.js
- ui/src/components/admin/DataDictionary/DictionaryDependentFieldValues.js
- ui/src/components/admin/DataDictionary/DictionaryFieldValues.js
- ui/src/components/admin/DataDictionary/DictionaryHeader.js
- ui/src/components/admin/DataDictionary/EditableFieldValue.js
- ui/src/theme/adminDictionaryStyles.js
- ui/src/theme/verticalTabStyles.js
🐛 Fixes the following bugs found in #609 :
- Maintain the "active" parent after editing a value with dependent fields (so you don't have to re-click the value to see its dependents)
- Fully reset the state upon clicking "Reset" (previously you could end up with a "Dependent Values" column corresponding to a value that no longer exists)
- Sort model form dropdown menu options
💄 Makes the following changes based on feedback from Kim and Rosi:
- Add spacing above footer
- Rearrange dictionary header components
- Show an indicator beside editable fields whose dependents have been modified
- Updated "Publish" modal copy
- Display the name of the value whose dependent fields are being shown (e.x. "Dependent Fields for Ampulla of Vater")
> 🐛+💄 Bug fixes and improvements for #609

- ui/src/components/admin/Model/AdminModelNav.js
💄 Also move the tooltips to the right so they don't get clipped on smaller window sizes
> 🐛 Fix tooltip crash on Create a Model page (#616)

- ui/src/components/Search.js
- ui/src/index.css
* Force `overflow-y: scroll` on root and search-results-wrapper so that 100vw styles respect scrollbar width
> 🐛 Fix search page content resizing on filtering (#703)

- ui/src/theme/modelStyles.js
Prevents section headers on the Model Details page from overlapping the content of other sections on smaller screen sizes
> 🐛 Fix model section header overlap on smaller screens (#728)

- cms/src/helpers/genomicVariants.js
- ui/src/components/VariantTables.js
- ui/src/providers/Variants.js
- ui/src/utils/constants.js
💄 Reorder Variants Tabs on Model Details Page, only show tabs if there is data (#653 & #683)
* Reorder the tabs in the Variants Table on the Model Details Page
* Rename "Genomic Sequencing" to "Research Somatic Variants"
* Hide tabs and display empty state when there is no variant/gene data available
🚧 Update Variant Tables to support somatic variant data (#653)
* Move VARIANT_TYPES to constants file
* Update columns for Research Somatic Variants table
* Add dummy data generator for RSVs
* Temporarily display dummy RSVs to test pagination of table
✨ Front-end model details page genomic variants API integration (#653)
* Remove dummy genomic variant data generator
* Connect RSV table to API
> Model Details Page GVI API Integration (#653)

- cms/src/routes/genomicVariants.js
- cms/src/services/gdc-importer/VariantImporter.js
- ui/src/components/TableDistributorCell.js
- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/Model/actions/ImportGenomicVariants.js
- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/index.js
- ui/src/providers/Variants.js
- ui/src/utils/constants.js
- ui/src/utils/useInterval.js
~Pretty close, but still a few things to work on. Namely, there seems to be a bug with the acknowledge endpoint that's causing the polling functionality to get stuck right now. Need to add some more error handling as well. There's also a temporary "Clear Import Notification" button on the CMS model page that will be removed once the acknowledge bug is gone.~
**Update: the acknowledge bug has been fixed and the "Clear Import Notification" has been removed. The "happy path" for a successful genomic variant import is working now 🎉** 
Commits:
- 🔒 Add rel="noopener noreferrer" to external link to Distributor
- 🔊 Update logging for genomic variant import in CMS
- ✨ Connect CMS Import Research Somatic Variants to API (#663)
* Add front-end functions to make API calls to GVI import API
* Add …
> ✨ Front-end for CMS Genomic Variant Import (#663) (#658) (#660)

- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js
- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/Notifications/index.js
- ui/src/providers/Variants.js
* Refactor all genomic variant import notification code to the admin-only NotificationsContext
* Split removeImportNotification into separate functions for removing the import notification and showing the successful import notification
> 🐛 Refactor to remove shared code between admin and non-admin for Genomic Variants

- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/charts/TopVariantsChart.js
💄 Change max value on top variants chart back to max number of variants instead of pretty number
✨ Trigger an update of genomic variant data on import completion
* If on the CMS page for the model whose import has just completed, fetch and display the latest data
> Variant Chart Update & Data Refresh on Import Completion

- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/modals/ConfirmationModal.js
* Add `confirmationRequired` prop to ConfirmationModal to conditionally show the confirmation modal
* Show confirmation modal only if there is an existing list of genomic variants of length > 0
> ✨ Add confirmation modal when overwriting existing genomic variants (#734)

- ui/src/components/App.js
- ui/src/components/Header.js
- ui/src/components/ModelBar.js
- ui/src/components/VariantTables.js
- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/input/Toggle/Toggle.js
- ui/src/components/search/ExpandedToggle.js
- ui/src/components/search/Search.js
- ui/src/providers/ExpandedUnexpanded.js
- ui/src/theme/adminNotificationStyles.js
- ui/src/theme/searchStyles.js
- ui/src/utils/sqonHelpers.js
In order to replicate SQON functionality (i.e. persisting on refresh of search page, persisting on clicking "Back to Search" link on Model Details page header, resetting on clicking the HCMI logo in the main header), the state of the expanded/unexpanded toggle was moved to localStorage and can now be accessed using a shared context.
The count for the number of unexpanded models has also been updated to reflect changes that are applied to search.
The bug where clicking the "Back to Search" link in the Model Details page header would sometimes still show the expanded status in the SQON has also been fixed.
Commits:
- ✨ Persist toggle state on navigation and refresh (#697)
* Move Expanded/Unexpanded toggle state to a shared context
* Persist toggle state by storing it in localStorage
- 🐛 …
> ✨ Persist Expanded/Unexpanded Toggle State, Update Unexpanded Model Count with Filters

- ui/src/components/VariantTables.js
🐛 Fix display priority for variant tabs (#789)
* If there are both Clinical and Research variants for a model, defauly to the Research variants tab
💄 Add loading state inside tabs of Variant Table on Model Details page (#789)
> 🐛 Model Details Page Bugfixes (#789)

- ui/src/components/App.js
- ui/src/components/Model.js
- ui/src/components/SkipNav.js
- ui/src/components/admin/AdminView.js
- ui/src/components/search/Search.js
- ui/src/theme/adminStyles.js
- ui/src/theme/searchStyles.js
- ui/src/theme/skipNavStyles.js
Set the "main" content as the following:
Search page -> search results column
Model details page -> content immediately after header nav
Admin pages -> content immediately after admin nav
Link is visually hidden until it receives focus, clicking the link sets focus to the element designated as "main" above.
> ♿️ Add "Skip to Main Content" skip nav link

- cms/src/helpers/genomicVariants.js
- cms/src/services/elastic-search/genomicVariants.js
- ui/src/components/search/GeneSearch.js
This is an approach to handling the discrepancy in versions between our gene reference library version and that of the GDC variants we are importing. Instead of using the Gene Reference to populate details about genes, we will rely exclusively on data provided in the MAF. One immediate impact of this change is there will be no Gene Names (short text description) or synonyms available.
This modifies 3 pieces of code:
- Variant Import will now populate fields from the MAF that were taken from gene reference (or leave them blank if not availble in MAF)
- Search index publishing for genes and variants will rely solely on the published variant data, it will not supplement the gene documents with any data from the Gene Reference 
- The Gene text search display will remove synonyms and names …
> Modify genomic variant import and publish to use only MAF data

- ui/src/components/charts/GrowthChart.js
* Rewrite how data for Growth Chart is grouped to allow for grouping non-2-D-or-3-D into 'Other' properly
* Re-enable linter in Growth Chart, apply linter fixes
* Remove 2+ year old unused code, remove lodash dependency
> 🐛 Fix 'Other' Type in Growth Chart (#686)

- docker-compose.yml
- elasticsearch/arranger_metadata/columns-state.json
- ui/package.json
- ui/src/components/search/Search.js
- yarn.lock
Integrate feature update in Arranger Components to enable search table to store page size, column selections, and sort order in user's session storage.
Similar work needed on other non-arranger tables in HCMI UI still.
> Preserve user settings for search table in session storage

- cms/package.json
- cms/src/routes/genomicVariants.js
- cms/src/services/gdc-importer/gdcConstants.js
- data_model/package.json
- ui/package.json
- ui/src/components/admin/BulkUpload/BulkUploadInput.js
- ui/src/components/admin/BulkUpload/BulkUploadModal.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/Model/actions/GenomicVariants.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/ModelsManager/ModelsManager.js
- ui/src/utils/constants.js
- yarn.lock
Adds radio selection for "overwrite variants" option on Bulk Model Upload modal. Depending on the user's selection, this will trigger a bulk variant import for none/some/all of the models in the bulk upload Google sheet.
⬆️ Upgrade lodash
* Upgrade lodash from 4.17.19 to 4.17.21
✏️ Fix typo in bulk import response
✨ Add specific model genomic variant audit functionality
* Add POST endpoint to CMS for auditing specific models for genomic variants
✨ Allow for automatic variant imports after bulk model upload (#848)
* Update bulk model upload modal to allow the user to select whether or not they want to import variants for the models within the sheet
* Refactor bulk upload modal to use constants for bulk upload types
* Add front-end API calls for bulk variant import and genomic variant audit
> ✨ Update Bulk Model Upload Modal for Bulk Variant Import (#848)

- cms/src/services/gdc-importer/VariantImporter.js
- ui/src/components/admin/Notifications/NotificationToaster.js
- ui/src/components/modals/ConfirmMafFileModal.js
- ui/src/theme/adminNotificationStyles.js
Feature work for #855 to add the `Show X more/Hide X notification(s)` button when there are 5+ notifications on screen.
Also includes a fix for a bug that was causing actionable errors in bulk imports to be created incorrectly, and a quality of life enhancement to the Confirm MAF File table.
---
**🐛 Fix bulk import actionable errors async issue**
* Wait for `getTissueStatus` promise before spreading bulk imports onto failed list
**✨ Add Show/Hide Button for Long Notification Lists (#855)**
* Display only the 5 most recent notifications, unless the user clicks the toggle to show/hide more
**💄 Make MAF Files Easier to Select**
* Increase clickable area for Confirm MAF File radio buttons, center button in table column
> ✨ Add Show/Hide Button for Long Notification Lists (#855)

- cms/src/routes/genomicVariants.js
- cms/src/services/gdc-importer/VariantImporter.js
- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/Model/actions/GenomicVariants.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js
- ui/src/components/admin/Notifications/NotificationToaster.js
- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/VariantAudit/VariantAuditModal.js
- ui/src/components/modals/ConfirmMafFileModal.js
- ui/src/theme/adminModalStyles.js
- ui/src/theme/adminNotificationStyles.js
- ui/src/theme/searchStyles.js
- ui/src/utils/constants.js
Updates to the UI to make it play nicely with the CMS/API changes to variant/bulk variant imports.
- `ui/src/components/admin/Notifications/NotificationsController.js` is updated to support the new import status/progress object from the back/end. It also stores a state for non-actionable errors from bulk imports
- `ui/src/components/modals/ConfirmMafFileModal.js` has been created, and allows the content manager to resolve conflicts with MAF files 
- `ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js` **has the largest amount of changes.** New functions have been added to show, update, and remove the various new bulk import error notifications, while still maintaining functionality for individual imports
The rest of the changes are mostly refactoring, adding API …
> ✨ UI & Error Handling for Importing Bulk and Individual Model Variants (#852 #853 #847)

- cms/src/services/gdc-importer/VariantImporter.js
- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Model/actions/GenomicVariants.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js
- ui/src/components/admin/Notifications/NotificationToaster.js
- ui/src/components/admin/Notifications/ProgressBanner.js
- ui/src/theme/adminNotificationStyles.js
- ui/src/utils/constants.js
Adds the very long-awaited bulk import progress banner notification, and the slightly less long-awaited stop import button. Also includes some bug fixes and code cleanups.
**The polling interval has been reduced from 1s to 0.5s. In local testing this hasn't caused any issues, and allows the Progress Bar to show more granular import steps. If you think this can cause an issue, let me know and I'll revert it.**
---
* `ui/src/components/admin/Notifications/ProgressBanner.js` has been created as a new notification which appears above the list of the regular rendered notifications in `NotificationToaster.js`
---
**⚡️ Reduce polling interval for import status check**
* Decrease the time between intervals to show a more accurate representation of import progress
**🐛 Fix bug in import …
> ✨ Add Import Progress Banner and Stop Import Button (#849 #856)

- ui/src/components/admin/ModelsManager/ModelManagerController.js
* Fixes a bug where a call to import variants for an empty model list would be made
> 🐛 Prevent variant import from running when all bulk model uploads fail (#892)

- cms/src/services/gdc-importer/VariantImporter.js
- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js
- ui/src/components/admin/Notifications/NotificationToaster.js
- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/Notifications/ProgressBanner.js
- ui/src/components/admin/helpers/notifications.js
- ui/src/components/modals/ConfirmMafFileModal.js
- ui/src/utils/constants.js
Slightly a WIP, still working on fixes for two more issues:
* there is a brief moment when, after confirming a MAF file for a **bulk** import error, the error is dismissed but the state still has the error so the notification comes back for a few milliseconds before disappearing again
* similarly, for **individual** import errors, the above error can occur and prevent the model's variants table from refreshing after the import
Wanted to get this up quickly though to provide more time for code review.
Fixes the following:
* Fix inconsistencies in import error notifications not appearing or appearing multiple times by using the state as a single source of truth and ensuring unique ids with uuid
* Trigger a refresh of the Model Variants Table after resolving an import conflict for an …
> 🐛 More bugfixes for Bulk Variant Import UI (#890 #894 #893)

- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/Notifications/ProgressBanner.js
- ui/src/components/admin/VariantAudit/VariantAuditModal.js
- ui/src/components/admin/index.js
🐛 Only attempt to refresh models table on Model Management page (#901)
* Fixes a bug where the Progress Banner would attempt to access context of the Model Management page on a different page, causing the page to crash
🐛 Disable Import Button on Variant Audit Modal While Loading (#900)
* Properly sets the `loading` state when beginning the import, preventing multiple imports from being triggered
> 🐛 More Bulk Variant Import Bug Fixes (#900 #901)

- cms/src/routes/genomicVariants.js
- cms/src/services/gdc-importer/mafFiles.js
- ui/src/components/modals/ConfirmMafFileModal.js
🐛 Use Entity Submitter ID as Entity ID (#908)
* Fixes a bug where the wrong Entity ID was being displayed in the Confirm MAF File modal
🐛 Account for models created before genomic variant support was added in Audit (#908)
* Fixes a bug where models created before genomic variants were added to the model would be incorrectly classified by the genomic variant audit
> 🐛 Bug Fixes from Release 1.10 Feedback (#908)

- cms/src/helpers/dictionary.js
- cms/src/helpers/genomicVariants.js
- cms/src/helpers/matchedModels.js
- cms/src/hooks.js
- cms/src/services/elastic-search/publish.js
* Log only model name instead of the full model on CMS updates
* Log the number of genomic variants added/removed instead of the full list
> ⚡️ Reduce logging to improve CMS performance (#904)

- ui/src/components/Header.js
- ui/src/components/Model.js
- ui/src/components/search/Search.js
- ui/src/theme/headerStyles.js
♿️ Improve a11y of Molecular Characterizations Table (#880)
* Fixes an issue with an empty table header
♿️ Ensure appropriate heading levels are used (#880)
* Fixes an a11y issue where pages were missing a level 1 heading
♿️ Fix remaining Search page a11y issues (#880)
* Add landmark role for Search facets sidebar
* Hide nivo charts from screen readers, the library still isn't accessible
> ♿️ Accessibility Improvements (#880)

- cms/src/helpers/genomicVariants.js
- cms/src/services/gdc-importer/VariantImporter.js
- cms/src/services/gdc-importer/gdcConstants.js
* Make use of the `caseId` and `fileId` when performing a variant import to automatically save the Model URL, Sequence URL, and Somatic MAF URL
> ✨ Generate GDC URLs on Variant Import (#913)

- ui/package.json
- ui/src/components/modals/ModelListModal.js
- ui/src/components/search/Search.js
- ui/src/components/tooltips/InfoTooltip.js
- ui/src/components/tooltips/index.js
- ui/src/theme/searchStyles.js
- yarn.lock
**⬆️ Upgrade Arranger to v2.13.0 (#907)**
* Upgrades @arranger/components to v2.13.0 for custom facet header support
**🗑️ Remove unused import**
* Removes an unused import from ModelListModal to prevent linter warnings
**✨ Add Info Tooltips to Arranger Facet Headers (#907)**
* Adds "hover bubbles" to: Research Somatic Variant Type, Has Multiple Models, and Available Molecular Characterizations facet headers
> ✨ Add Info Tooltips to Arranger Facet Headers (#907)

- ui/src/components/search/Search.js
- ui/src/components/tooltips/index.js
Adds a hover bubble for the "Expansion Status" column of the Search table
> ✨ Add Info Tooltip to Expansion Status Column

- scripts/README.md
* Provide detailed information on how and when to run the various config scripts within `/scripts`
It's a little verbose, with repeated content for the optional args and messaging about running the scripts from the root directory of the project, but I felt that was a good idea in case someone went straight to the section about a specific script and didn't read anything else.
> 📝 Update README for `/scripts` directory

- yarn.lock
* Update non-dev dependencies requiring `ws` to no longer use vulnerable versions
> ⬆️  Update dependencies (#938)

- cms/src/routes/genomicVariants.js
- cms/src/services/gdc-importer/VariantImporter.js
- cms/src/services/gdc-importer/gdcConstants.js
- ui/src/components/admin/Model/ModelVariants.js
- ui/src/components/admin/Model/actions/GenomicVariants.js
- ui/src/components/admin/Notifications/GenomicVariantImportNotifications.js
- ui/src/components/modals/ManualImportMafModal.js
- ui/src/theme/adminNavStyles.js
- ui/src/utils/constants.js
Adds a means for the content manager to manually specify a MAF file from GDC to import.
**💄 Convert Model Research Somatic Variants Button to Dropdown (#936)**
* Convert the import Research Somatic Variants button to a dropdown to make room for the manual override
**✨ Back-end for Manual MAF Import (#936)**
* Extend `/import/:name` endpoint to accept a `fileId` and `filename` for the MAF file to import
* Add error handling for manual MAF file import errors
**✨ Front-end for Manual MAF Import (#936)**
* Add Manual MAF Import Modal
* Add front-end error handling for Manual MAF Import errors
> ✨ Manual MAF Import Override (#936)

- elasticsearch/arranger_metadata/columns-state.json
- ui/src/components/search/Search.js
* Sort the Catalog Search table by `# of Research Somatic Variants` by default instead of `Name`
Tested to ensure that it:
**Deployment note: this change will require the `updateEs` script to be run in order to take effect.**
> 🔧 Change Default Sort Column of the Catalog (#944)

- cms/src/schemas/model.js
- docker-compose.yml
- elasticsearch/arranger_metadata/aggs-state.json
- elasticsearch/arranger_metadata/columns-state.json
- elasticsearch/arranger_metadata/extended.json
- elasticsearch/modelsIndex.json
- ui/src/components/charts/TopVariantsChart.js
- ui/src/components/search/Search.js
- ui/src/components/tooltips/index.js
* Exclude genes which are exclusively Histopathological Biomarkers from the `# Mutated Genes Calculation`
* Exclude genes which are exclusively Histopathological Biomarkers from the `Most Frequently Mutated Genes` chart
* Create new aggregation `gene_metadata__mutated_genes`
* Add tooltip to `# Mutated Genes` column header in Search table
* Prevent local bucket size exceptions on the TopVariantsChart by increasing the `search.max_buckets` setting on the ES instance spun up by Docker
In order to deploy these changes, the following steps need to be run:
1) run the `updateEs` script
2) run the `republish` script
3) restart the api service
> 🗃️ Change Mutated Genes Calculation (#946) 

- cms/src/helpers/genomicVariants.js
- cms/src/routes/bulk.js
- cms/src/routes/sync-data.js
- cms/src/schemas/model.js
- cms/src/services/elastic-search/publish.js
- cms/src/validation/variant.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/helpers/modelForm.js
Optimize the "Publish" step in the CMS by doing the following:
- Eliminate double network call when directly clicking "Publish" after changing a model
- Track variant changes and only update gene search indices when necessary
As of right now, there are no additional steps required to deploy these changes.
**⚡️ Front-end Optimizations for CMS Publishing Process (https://github.com/nci-hcmi-catalog/portal/issues/984)**
* Separate `Save` and `Publish` operations to prevent unnecessarily repeating length operations when publishing
* Require the user to click `Save` before clicking `Publish` on a model
* Change `isFormReadyToPublish` requirements to disallow publishing when form is dirty
**⚡️ Reduce Frequency of Re-indexing Gene Search Indices …
> ⚡ CMS Publishing Optimizations (#984)

- cms/src/routes/action.js
- cms/src/routes/bulk.js
* Populate `variants.variant` before performing any model validation, ensuring variant data is in the correct format
> 🐛 Fix False Variant Validation Errors on Bulk Publish (#1006)

- ui/src/components/Footer.js
- ui/src/theme/searchStyles.js
Add new footer link and update footer styles to accommodate
For compliance with NIH IT's Vulnerability Disclosure Program, we must add a link to the HHS Vulnerability Disclosure policy page on the Footer of public facing pages.
URL: https://www.hhs.gov/vulnerability-disclosure-policy/index.html
Text: HHS Vulnerability Disclosure
From Eva:
> Alongside the vulnerability penetration testing, there is also an additional HHS requirement for the Searchable Catalog to contain a URL pointing to the “[HHS Vulnerability Disclosure](https://www.hhs.gov/vulnerability-disclosure-policy/index.html)" on the public facing page (footer). Is this something that can be incorporated into a future release?
> 📝 Add "HHS Vulnerability Disclosure" Link to Footer (#1008)

- cms/src/index.js
- cms/src/routes/index.js
- cms/src/routes/publish.js
- cms/src/services/elastic-search/publish.js
- cms/src/services/publish/Publisher.js
- cms/src/services/publish/constants.js
- cms/src/services/publish/helpers.js
- ui/src/components/admin/AdminView.js
- ui/src/components/admin/Model/ModelSingleController.js
- ui/src/components/admin/Model/ModelSingleHeader.js
- ui/src/components/admin/Model/actions/Publish.js
- ui/src/components/admin/Model/actions/PublishModel.js
- ui/src/components/admin/Model/actions/SaveModel.js
- ui/src/components/admin/ModelsManager/ModelColumns.js
- ui/src/components/admin/ModelsManager/ModelManagerController.js
- ui/src/components/admin/ModelsManager/ModelsManager.js
- ui/src/components/admin/Notifications/NotificationToaster.js
- ui/src/components/admin/Notifications/NotificationsController.js
- ui/src/components/admin/Notifications/ProgressBanner.js
- ui/src/components/admin/Notifications/PublishNotifications.js
- ui/src/components/admin/Notifications/PublishProgress.js
- ui/src/components/admin/Notifications/index.js
- ui/src/components/admin/index.js
- ui/src/utils/constants.js
In lieu of a detailed PR description, I've added PR comments on each file (where necessary).
The TL;DR is we've essentially duplicated the async "GDC Variants Importer" and repurposed it as a new async "Publisher" service. This new "Publisher" uses the same queue system, has its own `/publish` router with similar endpoints to the importer, but publishes models to ES instead of importing variants for them.
On the UI we've replaced all calls to the old publish endpoints with calls to the new async endpoints, removed any locking/freezing of the UI when publishing, added a "Publish Progress" banner similar to the one used for GDC import progress, and updated the ModelStatusPill component to display "Publish in Progress" for models that are currently being published.
Due to time constraints, …
> ✨ Async Publishing (#1000)

- ui/src/components/admin/Model/ModelSingleHeader.js
- ui/src/components/admin/Notifications/PublishProgress.js
* Fixes a bug where table/model data would not refresh after very fast publishes
> 🐛 Ensure Table/Model Data Refresh After Publish

- cms/src/validation/model.js
* Fixes a bug which would cause Bulk Import to fail for sheets that haven't set a value for Split Ratio or Tissue Status (which are not required fields, and should thus be nullable)
> 🐛 Make 'Split Ratio' and 'Tissue Status' Nullable

- ui/src/components/Footer.js
- ui/src/components/Model.js
- ui/src/components/VariantTables.js
- ui/src/components/tooltips/index.js
- ui/src/theme/searchStyles.js
Update Footer URLs, "Case Report Forms" URL, and "Visit ATCC to Express Interest" URL. Also updates the Footer responsive breakpoint as a result of the new Footer URL labels being longer.
No additional deploy steps are required.
> 🚚  Update External URLs (#1041)

- api/src/dataExport.js
* Decodes less than and greater than operators in sanitized SQON before JSON parsing to prevent `Unknown op` error when downloading exports from Arranger
Eva reported an issue (#1050) where she was unable to download the “Export” TSV from the models table. Turns out it’s an issue with the “Age of Diagnosis” filter sqon.
“Age of Diagnosis” is a numeric facet, so it adds `>=` and/or `<=`  operators to the sqon based on user input.
A couple years ago we [started sanitizing the request params](https://github.com/nci-hcmi-catalog/portal/blob/8f767a5ccfd5e9b6883545ec5d2547adf06167ea/api/src/dataExport.js#L40C53-L40C53) (`req.sanitize(req.body.params)`) to the api endpoint for triggering the TSV download. So it’s going from `<=` to `&lt;=` in the sqon string before being parsed into JSON and …
> 🐛 Fix Exports With "Age at Diagnosis" Filter (#1050)

- cms/variant-migrations/migrations/20230929213342-update-molecular-characterizations-2.js
- cms/variant-migrations/migrations/20230929214009-rename-dna-methylation-2.js
* Migrations to update the Molecular Characterization options and individual model selections after a regression caused old "DNA Methylation Array" data to reappear
1. Deploy the new tag through Jenkins
3. Run the `20230929213342-update-molecular-characterizations-2.js`, and `20230929214009-rename-dna-methylation-2.js` migrations:
```
cd cms/variant-migrations
./../node_modules/.bin/migrate-mongo up -f migrate-mongo-config.js
```
4. Restart the cms service
5. Run the `republish` script
```
ENV={env} npm run republish
```
> 🗃️ Migrations to Fix DNA Methylation Data Regression (#1054)

- cms/variant-migrations/migrations/20240109040115-update-models-dna-methylation.js
- cms/variant-migrations/migrations/20240109040219-update-dictionary-dna-methylation.js
- cms/variant-migrations/migrations/20240109040313-update-dictionaryDraft-dna-methylation.js
The "DNA Methylation Array" molecular characterization terminology regressed again! This time, with Eva's help, we were able to identify the root cause as the Data Dictionary publishing a Draft containing the outdated values. Previously, the migrations had only updated the `models` and the `dictionary`. This time we'll update the `dictionaryDraft` as well, eliminating any traces of the old terminology for good.
**🗃️ Migrations to Fix "DNA Methylation Array" Terminology Regression (#1063)**
* Adds three migrations to fix the "DNA Methylation Array" molecular characterization regression that was caused by outdated Dictionary Drafts publishing old values
* `update-models-dna-methylation` updates any models containing the outdated terminology
* `update-dictionary-dna-methylation` updates the …
> 🗃️ Migrations to Fix "DNA Methylation Array" Terminology Regression (#1063)

- cms/variant-migrations/migrations/20240226184341-update-models-gdc-v1-sequence-urls.js
* Adds a migration to rewrite all model `source_sequence_url`s to use GDC v1
1. Deploy the new tag through Jenkins
2. Run the `20240226184341-update-models-gdc-v1-sequence-urls.js` migration:
```
cd cms/variant-migrations
./../node_modules/.bin/migrate-mongo up -f migrate-mongo-config.js
```
3. Restart the cms service
4. Run the `republish` script
```
ENV={env} npm run republish
```
> 🗃️ Rewrite Model Sequence URLs to GDC v1

- cms/src/helpers/uploadTemplate.js
- cms/src/schemas/descriptions/model.js
- cms/src/schemas/model.js
- cms/src/validation/model.js
- elasticsearch/arranger_metadata/aggs-state.json
- elasticsearch/arranger_metadata/columns-state.json
- elasticsearch/arranger_metadata/extended.json
- elasticsearch/modelsIndex.json
- ui/src/components/Model.js
- ui/src/components/admin/Model/ModelForm.js
- ui/src/components/queries/ModelListModalQuery.js
- ui/src/components/queries/ModelQuery.js
Adds a new field `proteomics_url` to the model, enabling a new External Resource link on the Model Details page, "Proteomics Data".
* Adds a new field to the model `proteomics_url` for linking to the GDC resources containing the proteomics data for this model
* Updates relevant es/arranger metadata
* Updates CMS to support adding this URL to a model
* Updates the Model Details page to display this link if the `ENABLE_PROTEOMICS` flag is enabled
1. Deploy the new tag through Jenkins
2. Run the `updateEs` script
```
ENV={env} npm run updateEs
```
3. Restart the api and cms services
> ✨ Add Proteomics Data URL to External Resources

- cms/src/helpers/genomicVariants.js
- cms/variant-migrations/migrations/20240708184150-update-models-gdc-v2-sequence-urls.js
The HCMI "Model Details" page (e.g. https://hcmi-searchable-catalog.nci.nih.gov/model/HCM-BROD-0648-C71) contains a "Sequencing Files" link under the "External Resources" section that previously pointed to a GDC v1 search filtered on the files related to the GDC Case ID of that model.
With the release of GDC v2, the ability to deep link to a search with file filters was deprecated.
GDC has since added a "Files" table to the "Case" page for a given Case ID, allowing us to link directly to that table and replace the functionality we had with v1.
This PR migrates existing links to the new format, and ensures new links will be created appropriately.
* Adds a migration to rewrite existing model `source_sequence_url`s to point to the new Files table on GDC v2's Case ID page
* Updates the …
> 🗃️ Rewrite Model "Sequencing Files" URLs to GDC v2

- ui/src/components/admin/AdminNav.js
* Uses a `nav` tag as the wrapper for the Admin/CMS navigation for better a11y, addressing the "Moderate" issue found in the [axe devtools](https://www.deque.com/axe/devtools/) automated scan for the 2023/2024 508 compliance report
> ♿️ Use `nav` Landmark Element for Admin Navigation

- ui/src/components/Model.js
* Adds the "External Link" icon to the ATCC external resource pill on the Model Details page
> 💄 Add "External Link" Icon to ATCC External Resource Pill

- api/package.json
- ui/package.json
- yarn.lock
* Pins `@overture-stack/arranger-server` and `@overture-stack/arranger-components` to v3.0.0-beta.36 and v3.0.0-beta.37 respectively
* This avoids the `jsonpath-plus` v10 incompatibility issue with Node.js v16
> 📌 Pin Arranger 3 Version

- api/package.json
- ui/package.json
- yarn.lock
Contains a hotfix pinning `@overture-stack/arranger-server` and `@overture-stack/arranger-components` to v3.0.0-beta.36 and v3.0.0-beta.37, respectively to avoid the `jsonpath-plus` dependency Node 16 incompatibility issue.
> 🔖 Release 1.26.1

- elasticsearch/arranger_metadata/extended.json
Updates Arranger Metadata extended config for field `gender` to display as `Sex`
No changes to Data Dictionary / Model Admin
Issue: https://github.com/nci-hcmi-catalog/portal/issues/1116
🚨 DEPLOYMENT INSTRUCTIONS 🚨
In order to deploy these changes, the following steps need to be run:
Run the updateEs script
`ENV={env} npm run updateEs`
> #1116 Update gender displayName

- ui/src/components/admin/DeleteModal/DeleteModal.jsx
- ui/src/components/admin/Model/ModelSingleController.jsx
- ui/src/components/admin/Model/actions/PublishModel.jsx
- ui/src/components/admin/ModelsManager/ModelManagerController.jsx
- ui/src/components/admin/helpers/modelForm.js
**Note: these might not be the _best_ solutions for all of these, I just wanted to highlight where the issues were (and what they were). Feel free to suggest or push better/cleaner/safer fixes!**
* Re-add `import React from 'react';` to `DeleteModal.jsx`
* Fix breaking bug on Admin forms related to `isFormReadyToSave` helper function (provide empty object fallback for when `errors` is undefined)
* Provide empty object fallback for when `errors` is undefined in `ModelSingleController.jsx`, `PublishModel.jsx`
* Use optional chaining for `errors.length` in `modelForm.js`
> 🐛🦺 Fix Breaking UI Bugs Related to Unsafe Vanilla JS
